version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "America/New_York"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "America/New_York"
    groups:
      npm:
        patterns:
          - "*"
